CREATE DATABASE web_analytics;
use web_analytics;

select * from ecommerce_new
limit 10;

select count(distinct user_id) as total_users
from ecommerce_new;
/* it gives total number of unique users */

select count(distinct user_id) as total_sessions
from ecommerce_new;
/* it gives number of sessions users had */

select event_type, count(*) as total_events
from ecommerce_new
group by event_type;
/* it gives event distribution */

select round(sum(conversion) * 100.0 / count(*), 2) as conversion_rate
from ecommerce_new;
/* it gives % of users who purchased */

select category_code, count(*) as total
from ecommerce_new
group by category_code
order by total desc
limit 10;
/* it gives top 10 categories */

select brand, count(*) as total
from ecommerce_new
group by brand
order by total desc
limit 10;
/* it gives top 10 brands purchased */

select round(sum(price),2) as total_revenue
from ecommerce_new
where event_type = 'purchase';
/* it gives revenue generated by users who purchased */

select
count(case when event_type='view' then 1 end) as views,
count(case when event_type='cart' then 1 end) as carts,
count(case when event_type='purchase' then 1 end) as purchases
from ecommerce_new;
/* it gives funnel analysis which means journey of users */

select
(views - carts) as drop_view_to_cart,
(carts - purchases) as drop_cart_to_purchases
from(
select
count(case when event_type='view' then 1 end) as views,
count(case when event_type='cart' then 1 end) as carts,
count(case when event_type='purchase' then 1 end) as purchases
from ecommerce_new
) as funnel;
/* it gives drop-off analysis of users from view-cart-purchase */

select date(event_time) as DATE, count(*) as traffic
from ecommerce_new
group by date(event_time)
order by DATE;

select user_id, count(*) as top_users
from ecommerce_new
group by user_id
order by top_users desc
limit 10;
/* it gives list of most active users */










